### ISSUE TITLE
Contribuir

### ISSUE THREAD

**Issue by elsantiF** [Tomas3w/posta-engine#2]
Hola buen día, encontré de casualidad este repo y me gustaría contribuir al código. Tengo la idea de hacer mi propio motor, pero busqué alguno que esté empezando (y en español) para ayudar a hacerlo. No sé cuál es la idea de ustedes y si quieren que se sume alguien más al desarrollo. Saludos.

**Comment by Tomas3w** [comment]
Buen día! Perdón por responder tan tarde, estuve muy ocupado con mi carrera y no he podido prestar mucha atención al motor ni al repo. Actualmente el motor esta en una época muy temprana en su desarrollo, así que hay aun mucho espacio para mejoras. Además no tiene interfaz gráfica, sino que es mas bien una herramienta de consola.
La idea del proyecto es la de construir un motor de videojuegos que fuera lo mas intuitivo posible (tanto como C++ lo permita) y que de la oportunidad a cualquiera de hacer un videojuego con los mínimos conocimientos sobre gráficos 3D y experiencia en C++. No es un motor para principiantes, sino que esta enfocado en dar la maxima libertad posible a los desarrolladores sin comprometer los detalles de mas bajo nivel asociados a crear videojuegos.
Es un motor modular, donde los diferentes componentes del mismo están divididos en distintas clases, cada una cumpliendo una función y nada más.

Como dije antes, estoy algo ocupado como para mejorar el motor, pero si queres saber mas no dudes en preguntar. Ahora voy a estar mas atento al repo asi que si preguntas no tendras que esperar dos meses XD.

**Comment by elsantiF** [comment]
Buenas! Mejor tarde que nunca xD. Entiendo la idea que tenes con el motor, no sé si tenés algún tipo de roadmap con las features o similar. Te aviso que clone el repo y para compilar el motor me dice que no está instalado zlib ni libpng, voy a depurar a ver si puedo solucionarlo y abro un PR.

**Comment by Tomas3w** [comment]
Por ahora no tenia nada planeado la verdad, hice el motor el verano pasado con un plan en mente, pero ahora he ido agregando pequeños cambios poco a poco sin ningún plan en particular. Es raro que no instale automaticamente el zlib y libpng.
El motor también funciona en linux pero no esta documentado esa parte y necesita de algunos cambios para funcionar ahí.
